#%RAML 1.0 NamedExample

{
  "name": "John Doe",
  "email": "john@gmail.com",
  "number": "000999657643",
  "phone": "9999888800",
  "fax": "5555666677",
  "billingAddress": {
    "street": "Sohna Road",
    "city": "Gurugram",
    "state": "Haryana",
    "postalCode": "500089",
    "countryIso": "India"
  },
  "shippingAddress": {
    "street": "Sohna Road",
    "city": "Gurugram",
    "state": "haryana",
    "postalCode": "500089",
    "countryIso": "India"
  }
}